# Generated by Django 4.0.1 on 2022-04-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='limit',
            field=models.IntegerField(default=100000, verbose_name='制限人数'),
        ),
    ]
