# Generated by Django 4.0.1 on 2022-06-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.IntegerField(blank=True, verbose_name='制限人数'),
        ),
    ]
